# Generated by Django 4.1.7 on 2023-04-02 16:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Имя автора')),
                ('language', models.CharField(max_length=20, verbose_name='Язык')),
                ('bio', models.TextField(verbose_name='Биография')),
            ],
            options={
                'verbose_name': 'Автор',
                'verbose_name_plural': 'Авторы',
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('language', models.CharField(max_length=20, verbose_name='Язык')),
                ('short_content', models.TextField(verbose_name='Краткое описание')),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Цена')),
                ('author', models.ManyToManyField(related_name='book', to='bookstory.author')),
            ],
            options={
                'verbose_name': 'Книга',
                'verbose_name_plural': 'Книги',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Имя')),
                ('phone', models.CharField(max_length=11, verbose_name='Номер телефона')),
                ('date_and_time', models.DateTimeField(default=datetime.datetime(2023, 4, 2, 19, 37, 23, 936746), verbose_name='дата заказа')),
                ('book', models.ManyToManyField(related_name='book', to='bookstory.book')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
    ]
